# Generated by Django 2.0 on 2019-04-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=128)),
                ('rut', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=256)),
                ('correo', models.CharField(max_length=256)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueEntregado', models.BooleanField(default=False)),
                ('fechaPedido', models.DateField()),
                ('fechaDespacho', models.DateField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappweb.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=256)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappweb.Proveedores'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappweb.Productos'),
        ),
    ]
